# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-15 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decomp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='motifset',
        ),
        migrations.DeleteModel(
            name='MotifSetList',
        ),
    ]
