# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decomp', '0003_motiflist_q_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedetail',
            name='motif_count',
        ),
    ]
