# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experimentName', models.TextField(max_length=128, unique=True)),
                ('resultId', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FileDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.TextField()),
                ('category', models.TextField()),
                ('motif_count', models.IntegerField(default=300, null=True)),
                ('experimentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Experiment')),
            ],
        ),
    ]
