# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('fileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.FileDetail')),
            ],
        ),
        migrations.CreateModel(
            name='MotifList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MotifName', models.TextField()),
                ('experimentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='alphatable',
            name='mass2motif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.MotifList'),
        ),
    ]
