# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170725_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='motiflist',
            name='MotifId',
            field=models.IntegerField(default=1),
        ),
    ]
