# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_experiment_motif_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='alpha_variance',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='motif_score',
        ),
        migrations.AddField(
            model_name='motiflist',
            name='motif_score',
            field=models.TextField(null=True),
        ),
    ]
