# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20170728_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motiflist',
            name='motif_score',
        ),
        migrations.AddField(
            model_name='motiflist',
            name='p_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='motiflist',
            name='t_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='motiflist',
            name='z_score',
            field=models.FloatField(null=True),
        ),
    ]
