# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-04 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_auto_20170802_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='motiflist',
            name='Annotation',
            field=models.TextField(null=True),
        ),
    ]
