# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_motiflist_annotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='category',
        ),
        migrations.AlterField(
            model_name='filedetail',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
